# Generated by Django 5.2.16 on 2026-07-13 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='Short code for quick entry, e.g. CBC, LFT', max_length=20, unique=True)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('semen', 'Semen'), ('other', 'Other')], default='blood', max_length=20)),
                ('department', models.CharField(blank=True, help_text='E.g., Hematology, Biochemistry, Microbiology', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=list, help_text='List of parameter dicts: [{"name": "Hemoglobin", "unit": "g/dL", "ref_min": 12.0, "ref_max": 16.0}, ...]')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Test (Catalog)',
                'verbose_name_plural': 'Test Catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated: LF-YYYYMMDD-NNNN', max_length=30, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(help_text='For SMS notification', max_length=15)),
                ('address', models.TextField(blank=True)),
                ('referred_by', models.CharField(blank=True, help_text='Referring doctor, if any', max_length=200)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('approved_by_chamber', 'Approved by Chamber'), ('sent_to_collection', 'Sent to Collection'), ('doctor_reviewed', 'Doctor Reviewed'), ('report_ready', 'Report Ready'), ('report_delivered', 'Report Delivered')], db_index=True, default='registered', max_length=30)),
                ('report_token', models.CharField(blank=True, db_index=True, editable=False, help_text='Unguessable token for public PDF download', max_length=64)),
                ('report_token_created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this visit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('testing', 'Testing'), ('result_entered', 'Result Entered'), ('doctor_reviewed', 'Doctor Reviewed'), ('retest_required', 'Retest Required'), ('recollection_required', 'Recollection Required'), ('report_ready', 'Report Ready')], db_index=True, default='pending', max_length=30)),
                ('result_value', models.JSONField(blank=True, help_text='Test results as JSON. Keys = parameter names, values = result strings.', null=True)),
                ('original_value', models.JSONField(blank=True, editable=False, help_text='Preserved original result if doctor made corrections.', null=True)),
                ('result_entered_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.testcatalog')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='core.visit')),
            ],
            options={
                'verbose_name': 'Test Order',
                'verbose_name_plural': 'Test Orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('semen', 'Semen'), ('other', 'Other')], max_length=20)),
                ('container_number', models.CharField(help_text='Number written on the physical container', max_length=50)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.visit')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Online')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.visit')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='E.g., status_changed, result_edited, payment_confirmed', max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('details', models.TextField(blank=True, help_text='Additional context about this action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('test_order', models.ForeignKey(blank=True, help_text='If this log entry is about a specific test order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.testorder')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.visit')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
