# Generated by Django 5.2.16 on 2026-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('approved_by_chamber', 'Approved by Chamber'), ('sent_to_collection', 'Sent to Collection'), ('sample_collected', 'Sample Drawn'), ('doctor_reviewed', 'Doctor Reviewed'), ('report_ready', 'Report Ready'), ('report_delivered', 'Report Delivered')], db_index=True, default='registered', max_length=30),
        ),
    ]
