# Generated by Django 5.2.16 on 2026-07-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Custom display order of the test order', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('approved_by_chamber', 'Approved by Chamber'), ('sent_to_collection', 'Sent to Collection'), ('sample_collected', 'Sample Drawn'), ('doctor_reviewed', 'Doctor Reviewed'), ('pending_reporting', 'Pending Reporting'), ('report_ready', 'Report Ready'), ('report_delivered', 'Report Delivered')], db_index=True, default='registered', max_length=30),
        ),
    ]
