# Generated by Django 5.2.16 on 2026-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testorder_display_order_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('testing', 'Testing'), ('result_entered', 'Result Entered'), ('doctor_reviewed', 'Doctor Reviewed'), ('retest_required', 'Retest Required'), ('recollection_required', 'Recollection Required'), ('report_ready', 'Report Ready'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
    ]
