# Generated by Django 5.2.16 on 2026-07-17 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cancelled_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient_name'], name='idx_visit_patient_name'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['phone'], name='idx_visit_phone'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-created_at'], name='idx_visit_created_desc'),
        ),
    ]
