# Generated by Django 5.2.16 on 2026-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visit_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcatalog',
            name='parameter_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of auto-calculation groups: [{"total": 4, "members": ["Albumin", "Globulin"]}, {"total": "Total Protein", "members": ["Albumin", "Globulin"]}]'),
        ),
    ]
